#!/bin/bash
# TRACKER MONITORING COMMANDS
# Run these from: /Users/geniustarigan/.openclaw/workspace

echo "============================================================================"
echo "TRACKER MONITORING COMMANDS"
echo "============================================================================"
echo ""
echo "📊 OPTION 1: DUAL TRACKER (Score-based, probabilistic)"
echo "════════════════════════════════════════════════════════════════════════════"
echo "Command:"
echo "  cd /Users/geniustarigan/.openclaw/workspace && python3 dual_tracker_immutable_dynamic.py --save"
echo ""
echo "What it shows:"
echo "  • IMMUTABLE BASELINE: Pre-enhancement scores (locked forever)"
echo "  • DYNAMIC TRACKER: Live post-enhancement scores"
echo "  • Per-filter failure rates (inferred from avg score)"
echo "  • Phase coverage (12/20 → 16/20 with Phase 4)"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "🔍 OPTION 2: FILTER PERFORMANCE VALIDATOR (Real daemon log counts) ✅"
echo "════════════════════════════════════════════════════════════════════════════"
echo "Command:"
echo "  cd /Users/geniustarigan/.openclaw/workspace && python3 filter_performance_validator.py"
echo ""
echo "What it shows:"
echo "  • ACTUAL per-filter fire counts from daemon logs"
echo "  • Real PASS/FAIL metrics (not probabilistic)"
echo "  • Phase 1: 100% pass rate ✅"
echo "  • Phase 2: 100% pass rate ✅"
echo "  • Phase 4: 100% pass rate ✅ (just deployed)"
echo "  • Phase 3: 19-38% pass rate ⏳ (pending)"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📈 OPTION 3: LIVE MONITORING (continuous 60s refresh)"
echo "════════════════════════════════════════════════════════════════════════════"
echo "Command:"
echo "  cd /Users/geniustarigan/.openclaw/workspace && python3 dual_tracker_immutable_dynamic.py --watch --save"
echo ""
echo "What it shows:"
echo "  • Updates every 60 seconds"
echo "  • Dynamic tracker changes in real-time"
echo "  • Signal accumulation tracking"
echo "  • Press Ctrl+C to stop"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "🔄 DAEMON STATUS"
echo "════════════════════════════════════════════════════════════════════════════"
echo "Command (check if running):"
echo "  ps aux | grep main.py | grep -v grep"
echo ""
echo "Command (tail logs):"
echo "  tail -50 /Users/geniustarigan/.openclaw/workspace/main_daemon.log | grep -E 'ENHANCED|Signal|phase'"
echo ""
echo "Command (count recent signals):"
echo "  tail -100 /Users/geniustarigan/.openclaw/workspace/main_daemon.log | grep -c 'Signal fired'"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
